# Do not build on tags
skip_tags: true

clone_folder: c:\projects\testify

build_script:
  - cd c:\projects\testify
  - nuget restore Testify.sln
  - msbuild Testify.sln /nologo /property:Configuration=Release

artifacts:
  - path: '**\*.nupkg'