# Do not build on tags
skip_tags: true

clone_folder: c:\projects\testify

install:
  - cd c:\projects\testify
  - ps: (new-object net.webclient).DownloadFile('https://github.com/dotnet/docfx/releases/download/v1.4/docfx.zip', 'docfx.zip')
  - 7z e docfx.zip

build_script:
  - cd c:\projects\testify
  - nuget restore Testify.sln
  - msbuild Testify.sln /nologo /property:Configuration=Release
  - cd docs
  - ..\docfx\docfx.exe metadata
  - ..\docfx\docfx.exe build
  - 7zr a "site.zip" "_site"
  - cd ..

artifacts:
  - path: 'src\**\*.nupkg'
  - path: 'docs\site.zip'